# Generated by Django 4.1.5 on 2023-02-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileName', models.CharField(max_length=20)),
                ('MobilePrice', models.IntegerField()),
                ('MobileModel', models.CharField(max_length=20)),
                ('MobileColor', models.CharField(max_length=20)),
            ],
        ),
    ]
