# Generated by Django 4.1.5 on 2023-02-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empname', models.CharField(max_length=20)),
                ('Empid', models.IntegerField()),
                ('Empemail', models.CharField(max_length=30)),
                ('Empnumber', models.IntegerField()),
            ],
        ),
    ]
